version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j_instance_test
    environment:
      NEO4J_AUTH: neo4j/kendallg  # Ensure consistent use of credentials
      NEO4JLABS_PLUGINS: '["graph-data-science", "apoc"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
    ports:
      - "127.0.0.1:7474:7474"  # HTTP, accessible only on localhost
      - "127.0.0.1:7687:7687"  # Bolt, accessible only on localhost
    volumes:
      - neo4j_data:/var/lib/neo4j  # Rename the volume to neo4j_data
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:7474"]
      #interval: 30s
      #timeout: 10s
      #retries: 5
    networks:
      - graphdb-network
    #volumes:
      #- ./data:/data
      #- ./logs:/logs
      #- ./import:/var/lib/neo4j/import
      #- ./plugins:/var/lib/neo4j/plugins
    #restart: unless-stopped
  python_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: python_instance_test
    volumes:
      - ./graph-ingest:/app
    depends_on:
      - neo4j
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
      #uvicorn API:app --host 0.0.0.0 --port 8000
    ports:
      #- "127.0.0.1:8000:8000"
      - "127.0.0.1:8888:8888"
    networks:
      - graphdb-network


volumes:
  neo4j_data:
    driver: local

networks:
  graphdb-network:
    driver: bridge